### ISSUE TITLE
Blocks no longer work in 4.6.3

### ISSUE THREAD

**Issue by bellamystudio** [spider-themes/advanced-accordion-block#1]
The accordion blocks only open in Firefox, in all other major browsers they are unresponsive. Unfortunately there are no javascript errors in the console to help diagnose the issue.

**Comment by delweratjk** [comment]
We have already solved the problem. This solution will be added in the next version. Thank you very much for pointing out the problem.

**Comment by jackappleby** [comment]
Still getting this issue on v 4.6.4 (Wordpress v 6.5) in Chrome

**Comment by jackappleby** [comment]
Update and fix: I got "unexpected content" block errors when I went to edit pages with accordions. "Attempt block recovery" button resolved the issue.

**Comment by delweratjk** [comment]
Yes, since the editor script has been updated, you have to update your previous version of code from the gutenberg editor like this. Thank you very much for your own understanding of the issue and the update. So we can close this topic. Feel free to contact us for any future problem.
Thank you again.
