### ISSUE TITLE
In 4.6.4 all of my accordion blocks now say "Your site doesn’t include support for the Group Accordion block."

### ISSUE THREAD

**Issue by bellamystudio** [spider-themes/advanced-accordion-block#2]
This plugin was working fine and in the last two updates you've managed to completely break it both times. I purchased the pro version thinking that would fix this and now I have no accordion block available to me in the page and all of the accordions are broken. Please can you address this as I have about 100 FAQs on a high traffic site that are once again not working

**Comment by delweratjk** [comment]
Sorry for your problem as you have been facing the problem for a couple of days. Please leave a screenshot of the problem for easy understanding. It will help to solve it quickly.
Thank you

**Comment by delweratjk** [comment]
This issue has been resolved. For your kind information, please update your blocks inside editor after receiving any update of our plugin. Because we often need to update JSON in our plugin. That's why Gutenberg's blocks will show update requests in editor. And if you update, the design will not break or cause any problems.
Thank you.
